apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- route.yaml
- namespace.yaml

patches:
- patch: |-
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: todo-backend-backup
    $patch: delete
  target:
    kind: CronJob
    name: todo-backend-backup
images:
- name: joelheusala/broadcaster
  newName: joelheusala/broadcaster
  newTag: cbe733a11a213472ec1fc89a987fcd465da5b081
- name: joelheusala/todo-app
  newName: joelheusala/todo-app
  newTag: cbe733a11a213472ec1fc89a987fcd465da5b081
- name: joelheusala/todo-backend
  newName: joelheusala/todo-backend
  newTag: cbe733a11a213472ec1fc89a987fcd465da5b081
- name: joelheusala/wikipedia-reader
  newName: joelheusala/wikipedia-reader
  newTag: cbe733a11a213472ec1fc89a987fcd465da5b081
