apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: joelheusala/todo-app:4.5.2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:1234/todos"
            - name: IMG_PATH
              value: "/shared/img.jpg"
            - name: IMG_URL
              value: "https://picsum.photos/1200"
          volumeMounts:
            - name: shared-image
              mountPath: /shared
